### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by 1923812371283127398123712893126793** [mopsfl/GoofyLuaUglifier#2]
yeah

**Comment by mopsfl** [comment]
go here and use it
https://mopsfl.de/GoofyLuaUglifier/

**Comment by 1923812371283127398123712893126793** [comment]
> go here and use it https://mopsfl.de/GoofyLuaUglifier/

no i wanna host it

**Comment by mopsfl** [comment]
host what

**Comment by 1923812371283127398123712893126793** [comment]
> host what

i want to put goofyluauglifier in my own website**

**Comment by mopsfl** [comment]
the source code is not public but you may use the api: https://mopsfl.de/GoofyLuaUglifier/docs/

**Comment by 1923812371283127398123712893126793** [comment]
> the source code is not public but you may use the api: https://mopsfl.de/GoofyLuaUglifier/docs/

ok

**Comment by 1923812371283127398123712893126793** [comment]
resolved
